language: node_js
sudo: false

node_js:
  - '5.9.0'
  - 'stable'

script: 'npm run test-travis'
# Send coverage data to Coveralls

#after_script: 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'